info:
  contact: {}
  title: Learning API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: サーバーのヘルスチェック
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
  /images:
    get:
      consumes:
      - application/json
      description: ユーザーがアップロードした画像の一覧をBlob Storage から取得する。
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
  /images/{name}:
    get:
      consumes:
      - application/json
      description: 指定した画像の情報をBlob Storage から取得する。
      parameters:
      - description: Image Name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
    post:
      consumes:
      - application/json
      description: ユーザーがアップロードした画像をBlob Storageにアップロードする。Bodyにはbase64エンコードされた画像を要求する。
      parameters:
      - description: Image Name
        in: path
        name: name
        required: true
        type: string
      - description: Image Body
        in: body
        name: body
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Error decoding base64
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
  /images/{name}/delete:
    post:
      consumes:
      - application/json
      description: 指定した画像をBlob Storageから削除する。
      parameters:
      - description: Image Name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
swagger: "2.0"
